using System.ComponentModel;

namespace Oxide.Ext.Discord.WebSockets
{
    public enum DispatchCode : byte
    {
        Unknown,
        [Description("READY")] Ready,
        [Description("RESUMED")] Resumed,
        [Description("CHANNEL_CREATE")] ChannelCreated,
        [Description("CHANNEL_UPDATE")] ChannelUpdated,
        [Description("CHANNEL_DELETE")] ChannelDeleted,
        [Description("CHANNEL_PINS_UPDATE")] ChannelPinsUpdate,
        [Description("GUILD_CREATE")] GuildCreated,
        [Description("GUILD_UPDATE")] GuildUpdated,
        [Description("GUILD_DELETE")] GuildDeleted,
        [Description("GUILD_BAN_ADD")] GuildBanAdded,
        [Description("GUILD_BAN_REMOVE")] GuildBanRemoved,
        [Description("GUILD_EMOJIS_UPDATE")] GuildEmojisUpdated,
        [Description("GUILD_INTEGRATIONS_UPDATE")] GuildIntegrationsUpdated,
        [Description("GUILD_MEMBER_ADD")] GuildMemberAdded,
        [Description("GUILD_MEMBER_REMOVE")] GuildMemberRemoved,
        [Description("GUILD_MEMBER_UPDATE")] GuildMemberUpdated,
        [Description("GUILD_MEMBERS_CHUNK")] GuildMembersChunk,
        [Description("GUILD_ROLE_CREATE")] GuildRoleCreated,
        [Description("GUILD_ROLE_UPDATE")] GuildRoleUpdated,
        [Description("GUILD_ROLE_DELETE")] GuildRoleDeleted,
        [Description("INTEGRATION_CREATE")] IntegrationCreated,
        [Description("INTEGRATION_UPDATE")] IntegrationUpdated,
        [Description("INTEGRATION_DELETE")] IntegrationDeleted,
        [Description("MESSAGE_CREATE")] MessageCreated,
        [Description("MESSAGE_UPDATE")] MessageUpdated,
        [Description("MESSAGE_DELETE")] MessageDeleted,
        [Description("MESSAGE_DELETE_BULK")] MessageBulkDeleted,
        [Description("MESSAGE_REACTION_ADD")] MessageReactionAdded,
        [Description("MESSAGE_REACTION_REMOVE")] MessageReactionRemoved,
        [Description("MESSAGE_REACTION_REMOVE_ALL")] MessageReactionAllRemoved,
        [Description("MESSAGE_REACTION_REMOVE_EMOJI")] MessageReactionEmojiRemoved,
        [Description("PRESENCE_UPDATE")] PresenceUpdated,
        [Description("PRESENCES_REPLACE")] PresenceReplace,
        [Description("TYPING_START")] TypingStarted,
        [Description("USER_UPDATE")] UserUpdated,
        [Description("VOICE_STATE_UPDATE")] VoiceStateUpdated,
        [Description("VOICE_SERVER_UPDATE")] VoiceServerUpdated,
        [Description("WEBHOOKS_UPDATE")] WebhooksUpdated,
        [Description("INVITE_CREATE")] InviteCreated,
        [Description("INVITE_DELETE")] InviteDeleted,
        [Description("INTERACTION_CREATE")] InteractionCreated,
        [Description("APPLICATION_COMMAND_CREATE")] ApplicationCommandCreated,
        [Description("APPLICATION_COMMAND_UPDATE")] ApplicationCommandUpdated,
        [Description("APPLICATION_COMMAND_DELETE")] ApplicationCommandDeleted,
        [Description("GUILD_JOIN_REQUEST_DELETE")] GuildJoinRequestDeleted,
    }
}